# Generated by Django 5.2.5 on 2025-08-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "enrollment_key",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("stu_annual_key", models.IntegerField()),
                ("staff_key", models.IntegerField()),
                ("course_key", models.IntegerField()),
                ("c_period", models.IntegerField()),
                ("school_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollment",
            },
        ),
    ]
