# Generated by Django 5.2.5 on 2025-08-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="c_period",
            field=models.CharField(max_length=10),
        ),
    ]
