# Generated by Django 5.2.5 on 2025-08-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_enrollment_c_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_key", models.IntegerField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("staff_key", models.IntegerField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "stu_annual_key",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("student_id", models.CharField(max_length=20)),
                ("student_name", models.CharField(max_length=255)),
                ("grade", models.IntegerField()),
                ("stu_email", models.EmailField(max_length=254)),
                (
                    "current_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "w_c_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("school_id", models.IntegerField()),
                ("school_year", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "student",
            },
        ),
    ]
